import { IChemicalElement }from "../interface";

const chemicalElements: IChemicalElement[] = [
    {
        symbol: "H",
        number: "1",
        ar: "1,00794",
        oxidation: ["1"],
        nameRu: "Водород",
        nameLa: "Hydragenium",
        radioactive: false,
        class: "s other no-metal",
    },
    {
        symbol: "He",
        number: "2",
        ar: "2,0026",
        oxidation: ["0"],
        nameRu: "Гелий",
        nameLa: "Helium",
        radioactive: false,
        class: "s noble gas",
    },
    {
        symbol: "Li",
        number: "3",
        ar: "6,941",
        oxidation: ["1"],
        nameRu: "Литий",
        nameLa: "Lithium",
        radioactive: false,
        class: "s alkaline metal",
    },
    {
        symbol: "Be",
        number: "4",
        ar: "9,0122",
        oxidation: ["2"],
        nameRu: "Бериллий",
        nameLa: "Beryllium",
        radioactive: false,
        class: "s",
    },
    {
        symbol: "B",
        number: "5",
        ar: "10,811",
        oxidation: ["3"],
        nameRu: "Бор",
        nameLa: "Borum",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "C",
        number: "6",
        ar: "12,0107",
        oxidation: ["4"],
        nameRu: "Углерод",
        nameLa: "Carboneum",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "N",
        number: "7",
        ar: "14,0067",
        oxidation: ["4"],
        nameRu: "Азот",
        nameLa: "Nitrogenium",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "O",
        number: "8",
        ar: "15,9994",
        oxidation: ["-2"],
        nameRu: "Кислород",
        nameLa: "Oxygenium",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "F",
        number: "9",
        ar: "18,9984",
        oxidation: ["-1"],
        nameRu: "Фтор",
        nameLa: "Fluorum",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "Ne",
        number: "10",
        ar: "20,1797",
        oxidation: ["1"],
        nameRu: "Неон",
        nameLa: "Neon",
        radioactive: false,
        class: "p noble gas",
    },
    {
        symbol: "Na",
        number: "11",
        ar: "22,9897",
        oxidation: ["1"],
        nameRu: "Натрий",
        nameLa: "Natrium",
        radioactive: false,
        class: "s alkaline metal",
    },
    {
        symbol: "Mg",
        number: "12",
        ar: "24,305",
        oxidation: ["2"],
        nameRu: "Магний",
        nameLa: "Magnesium",
        radioactive: false,
        class: "s alkaline metal",
    },
    {
        symbol: "Al",
        number: "13",
        ar: "26,9815",
        oxidation: ["3"],
        nameRu: "Алюминий",
        nameLa: "Aluminium",
        radioactive: false,
        class: "p",
    },
    {
        symbol: "Si",
        number: "14",
        ar: "28,0855",
        oxidation: ["4"],
        nameRu: "Кремний",
        nameLa: "Silicium",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "P",
        number: "15",
        ar: "30,9738",
        oxidation: ["5"],
        nameRu: "Фосфор",
        nameLa: "Phosphorus",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "S",
        number: "16",
        ar: "32,066",
        oxidation: ["6"],
        nameRu: "Сера",
        nameLa: "Sulfur",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "Cl",
        number: "17",
        ar: "35,45",
        oxidation: ["6"],
        nameRu: "Хлор",
        nameLa: "Chlorum",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "Ar",
        number: "18",
        ar: "39,948",
        oxidation: ["0"],
        nameRu: "Аргон",
        nameLa: "Argon",
        radioactive: false,
        class: "p noble gas",
    },
    {
        symbol: "K",
        number: "19",
        ar: "39,0983",
        oxidation: ["1"],
        nameRu: "Калий",
        nameLa: "Kalium",
        radioactive: false,
        class: "s alkaline metal",
    },
    {
        symbol: "Ca",
        number: "20",
        ar: "40,078",
        oxidation: ["2"],
        nameRu: "Кальций",
        nameLa: "Calcium",
        radioactive: false,
        class: "s alkaline earth metal",
    },
    {
        symbol: "Sc",
        number: "21",
        ar: "44,9559",
        oxidation: ["3"],
        nameRu: "Скандий",
        nameLa: "Scandium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Ti",
        number: "22",
        ar: "47,867",
        oxidation: ["4"],
        nameRu: "Титан",
        nameLa: "Titanium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "V",
        number: "23",
        ar: "50,9415",
        oxidation: ["5"],
        nameRu: "Ванадий",
        nameLa: "Vanadium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Cr",
        number: "24",
        ar: "51,9961",
        oxidation: ["3"],
        nameRu: "Хром",
        nameLa: "Cromium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Mn",
        number: "25",
        ar: "54,938",
        oxidation: ["2", "4"],
        nameRu: "Марганец",
        nameLa: "Manganum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Fe",
        number: "26",
        ar: "55,845",
        oxidation: ["2", "3"],
        nameRu: "Железо",
        nameLa: "Ferrum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Co",
        number: "27",
        ar: "58,9332",
        oxidation: ["2"],
        nameRu: "Кобальт",
        nameLa: "Cobaltum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Ni",
        number: "28",
        ar: "58,6934",
        oxidation: ["2"],
        nameRu: "Никель",
        nameLa: "Niccolum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Cu",
        number: "29",
        ar: "63,546",
        oxidation: ["2"],
        nameRu: "Медь",
        nameLa: "Cuprum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Zn",
        number: "30",
        ar: "65,38",
        oxidation: ["2"],
        nameRu: "Цинк",
        nameLa: "Zincum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Ga",
        number: "31",
        ar: "69,723",
        oxidation: ["3"],
        nameRu: "Галлий",
        nameLa: "Gallium",
        radioactive: false,
        class: "p",
    },
    {
        symbol: "Ge",
        number: "32",
        ar: "72,63",
        oxidation: ["4"],
        nameRu: "Германий",
        nameLa: "Germanium",
        radioactive: false,
        class: "p",
    },
    {
        symbol: "As",
        number: "33",
        ar: "74,9216",
        oxidation: ["3"],
        nameRu: "Мышьяк",
        nameLa: "Arsenicum",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "Se",
        number: "34",
        ar: "78,96",
        oxidation: ["4"],
        nameRu: "Селен",
        nameLa: "Selenium",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "Br",
        number: "35",
        ar: "79,904",
        oxidation: ["-1"],
        nameRu: "Бром",
        nameLa: "Bromum",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "Kr",
        number: "36",
        ar: "83,798",
        oxidation: ["2"],
        nameRu: "Криптон",
        nameLa: "Krypton",
        radioactive: false,
        class: "p noble gas",
    },
    {
        symbol: "Rb",
        number: "37",
        ar: "85,4678",
        oxidation: ["1"],
        nameRu: "Рубидий",
        nameLa: "Rubidium",
        radioactive: false,
        class: "s alkaline metal",
    },
    {
        symbol: "Sr",
        number: "38",
        ar: "87,62",
        oxidation: ["2"],
        nameRu: "Стронций",
        nameLa: "Strontium",
        radioactive: false,
        class: "s alkaline earth metal",
    },
    {
        symbol: "Y",
        number: "39",
        ar: "88,9059",
        oxidation: ["3"],
        nameRu: "Иттрий",
        nameLa: "Yttrium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Zr",
        number: "40",
        ar: "91,224",
        oxidation: ["4"],
        nameRu: "Цирконий",
        nameLa: "Zirconium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Nb",
        number: "41",
        ar: "92,9064",
        oxidation: ["5"],
        nameRu: "Ниобий",
        nameLa: "Niobium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Mo",
        number: "42",
        ar: "95,96",
        oxidation: ["6"],
        nameRu: "Молибден",
        nameLa: "Molybdaenum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Tc",
        number: "43",
        ar: "97,907",
        oxidation: ["7"],
        nameRu: "Технеций",
        nameLa: "Technetium",
        radioactive: true,
        class: "d transition metal",
    },
    {
        symbol: "Ru",
        number: "44",
        ar: "101,07",
        oxidation: ["4"],
        nameRu: "Рутений",
        nameLa: "Ruthenium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Rh",
        number: "45",
        ar: "102,9055",
        oxidation: ["3"],
        nameRu: "Родий",
        nameLa: "Rhodium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Pd",
        number: "46",
        ar: "106,42",
        oxidation: ["2"],
        nameRu: "Палладий",
        nameLa: "Palladium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Ag",
        number: "47",
        ar: "107,8682",
        oxidation: ["1"],
        nameRu: "Серебро",
        nameLa: "Argentum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Cd",
        number: "48",
        ar: "112,411",
        oxidation: ["2"],
        nameRu: "Кадмий",
        nameLa: "Cadmium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "In",
        number: "49",
        ar: "114,818",
        oxidation: ["3"],
        nameRu: "Индий",
        nameLa: "Indium",
        radioactive: false,
        class: "p",
    },
    {
        symbol: "Sn",
        number: "50",
        ar: "118,71",
        oxidation: ["4"],
        nameRu: "Олово",
        nameLa: "Stannum",
        radioactive: false,
        class: "p",
    },
    {
        symbol: "Sb",
        number: "51",
        ar: "121,76",
        oxidation: ["3"],
        nameRu: "Сурьма",
        nameLa: "Stibium",
        radioactive: false,
        class: "p",
    },
    {
        symbol: "Te",
        number: "52",
        ar: "127,6",
        oxidation: ["4"],
        nameRu: "Теллур",
        nameLa: "Tellurium",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "I",
        number: "53",
        ar: "126,9045",
        oxidation: ["-1"],
        nameRu: "Йод",
        nameLa: "Iodum",
        radioactive: false,
        class: "p other no-metal",
    },
    {
        symbol: "Xe",
        number: "54",
        ar: "131,29",
        oxidation: ["6"],
        nameRu: "Ксенон",
        nameLa: "Xenon",
        radioactive: false,
        class: "p noble gas",
    },
    {
        symbol: "Cs",
        number: "55",
        ar: "132,9055",
        oxidation: ["1"],
        nameRu: "Цезий",
        nameLa: "Caesium",
        radioactive: false,
        class: "s alkaline metal",
    },
    {
        symbol: "Ba",
        number: "56",
        ar: "137,327",
        oxidation: ["2"],
        nameRu: "Барий",
        nameLa: "Barium",
        radioactive: false,
        class: "s alkaline earth metal",
    },
    {
        symbol: "La",
        number: "57",
        ar: "138,9055",
        oxidation: ["3"],
        nameRu: "Лантан",
        nameLa: "Lanthanum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Ce",
        number: "58",
        ar: "140,116",
        oxidation: ["3"],
        nameRu: "Церий",
        nameLa: "Cerium",
        radioactive: false,
        class: "f-top lanthanide",
    },
    {
        symbol: "Pr",
        number: "59",
        ar: "140,9077",
        oxidation: ["3"],
        nameRu: "Празеодим",
        nameLa: "Praseodymium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Nd",
        number: "60",
        ar: "144,24",
        oxidation: ["3"],
        nameRu: "Неодим",
        nameLa: "Neodymium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Pm",
        number: "61",
        ar: "[145]",
        oxidation: ["3"],
        nameRu: "Прометий",
        nameLa: "Promethium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Sm",
        number: "62",
        ar: "150,36",
        oxidation: ["3"],
        nameRu: "Самарий",
        nameLa: "Samarium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Eu",
        number: "63",
        ar: "151,964",
        oxidation: ["3"],
        nameRu: "Европий",
        nameLa: "Europium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Gd",
        number: "64",
        ar: "157,25",
        oxidation: ["3"],
        nameRu: "Гадолиний",
        nameLa: "Gadolinium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Tb",
        number: "65",
        ar: "158,9253",
        oxidation: ["3"],
        nameRu: "Тербий",
        nameLa: "Terbium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Dy",
        number: "66",
        ar: "162,5",
        oxidation: ["3"],
        nameRu: "Диспрозий",
        nameLa: "Dysprosium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Ho",
        number: "67",
        ar: "164,9303",
        oxidation: ["3"],
        nameRu: "Гольмий",
        nameLa: "Holmium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Er",
        number: "68",
        ar: "167,26",
        oxidation: ["3"],
        nameRu: "Эрбий",
        nameLa: "Erbium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Tm",
        number: "69",
        ar: "168,9342",
        oxidation: ["3"],
        nameRu: "Тулий",
        nameLa: "Thulium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Yb",
        number: "70",
        ar: "173,045",
        oxidation: ["3"],
        nameRu: "Иттербий",
        nameLa: "Ytterbium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Lu",
        number: "71",
        ar: "174,967",
        oxidation: ["3"],
        nameRu: "Лютеций",
        nameLa: "Lutetium",
        radioactive: false,
        class: "f-top lanthanides",
    },
    {
        symbol: "Hf",
        number: "72",
        ar: "178,49",
        oxidation: ["4"],
        nameRu: "Гафний",
        nameLa: "Hafnium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Ta",
        number: "73",
        ar: "180,9479",
        oxidation: ["5"],
        nameRu: "Тантал",
        nameLa: "Tantalum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "W",
        number: "74",
        ar: "183,84",
        oxidation: ["6"],
        nameRu: "Вольфрам",
        nameLa: "Wolframium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Re",
        number: "75",
        ar: "186,207",
        oxidation: ["7"],
        nameRu: "Рений",
        nameLa: "Rhenium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Os",
        number: "76",
        ar: "190,23",
        oxidation: ["8", "4"],
        nameRu: "Осмий",
        nameLa: "Osmium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Ir",
        number: "77",
        ar: "192,217",
        oxidation: ["3", "4"],
        nameRu: "Иридий",
        nameLa: "Iridium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Pt",
        number: "78",
        ar: "195,084",
        oxidation: ["2", "4"],
        nameRu: "Платина",
        nameLa: "Platinum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Au",
        number: "79",
        ar: "196,966",
        oxidation: ["3"],
        nameRu: "Золото",
        nameLa: "Aurum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Hg",
        number: "80",
        ar: "200,59",
        oxidation: ["2"],
        nameRu: "Ртуть",
        nameLa: "Hydrargyrum",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Tl",
        number: "81",
        ar: "204,3833",
        oxidation: ["1"],
        nameRu: "Таллий",
        nameLa: "Thallium",
        radioactive: false,
        class: "p",
    },
    {
        symbol: "Pb",
        number: "82",
        ar: "207,2",
        oxidation: ["2"],
        nameRu: "Свинец",
        nameLa: "Plumbum",
        radioactive: false,
        class: "p",
    },
    {
        symbol: "Bi",
        number: "83",
        ar: "208,9804",
        oxidation: ["3"],
        nameRu: "Висмут",
        nameLa: "Bismuthum",
        radioactive: true,
        class: "p",
    },
    {
        symbol: "Po",
        number: "84",
        ar: "208,98",
        oxidation: ["4"],
        nameRu: "Полоний",
        nameLa: "Polonium",
        radioactive: true,
        class: "p",
    },
    {
        symbol: "At",
        number: "85",
        ar: "[210]",
        oxidation: ["4"],
        nameRu: "Астат",
        nameLa: "Astatium",
        radioactive: true,
        class: "p other no-metal",
    },
    {
        symbol: "Rn",
        number: "86",
        ar: "[222]",
        oxidation: ["2"],
        nameRu: "Радон",
        nameLa: "Radon",
        radioactive: true,
        class: "p noble gas",
    },
    {
        symbol: "Fr",
        number: "87",
        ar: "[223]",
        oxidation: ["1"],
        nameRu: "Франций",
        nameLa: "Francium",
        radioactive: true,
        class: "s alkaline metal",
    },
    {
        symbol: "Ra",
        number: "88",
        ar: "226,025",
        oxidation: ["2"],
        nameRu: "Радий",
        nameLa: "Radium",
        radioactive: true,
        class: "s alkaline earth metal",
    },
    {
        symbol: "Ac",
        number: "89",
        ar: "227,0278",
        oxidation: ["3"],
        nameRu: "Актиний",
        nameLa: "Actinium",
        radioactive: true,
        class: "d transition metal",
    },
    {
        symbol: "Th",
        number: "90",
        ar: "232,038",
        oxidation: ["4"],
        nameRu: "Торий",
        nameLa: "Thorium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Pa",
        number: "91",
        ar: "231,036",
        oxidation: ["5"],
        nameRu: "Протактиний",
        nameLa: "Protactinium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "U",
        number: "92",
        ar: "238,029",
        oxidation: ["6"],
        nameRu: "Уран",
        nameLa: "Uranium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Np",
        number: "93",
        ar: "237,048",
        oxidation: ["5"],
        nameRu: "Нептуний",
        nameLa: "Neptunium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Pu",
        number: "94",
        ar: "[244]",
        oxidation: ["3", "4"],
        nameRu: "Плутоний",
        nameLa: "Plutonium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Am",
        number: "95",
        ar: "[243]",
        oxidation: ["3"],
        nameRu: "Америций",
        nameLa: "Americium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Cm",
        number: "96",
        ar: "[247]",
        oxidation: ["3"],
        nameRu: "Кюрий",
        nameLa: "Curium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Bk",
        number: "97",
        ar: "[247]",
        oxidation: ["3"],
        nameRu: "Берклий",
        nameLa: "Berkelium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Cf",
        number: "98",
        ar: "[251]",
        oxidation: ["3"],
        nameRu: "Калифорний",
        nameLa: "Californium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Es",
        number: "99",
        ar: "[252]",
        oxidation: ["3"],
        nameRu: "Эйнштейний",
        nameLa: "Einsteinium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Fm",
        number: "100",
        ar: "[257]",
        oxidation: ["3"],
        nameRu: "Фермий",
        nameLa: "Fermium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Md",
        number: "101",
        ar: "[258]",
        oxidation: ["3"],
        nameRu: "Менделевий",
        nameLa: "Mendelevium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "No",
        number: "102",
        ar: "[259]",
        oxidation: ["2"],
        nameRu: "Нобелий",
        nameLa: "Nobelium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Lr",
        number: "103",
        ar: "[260]",
        oxidation: ["3"],
        nameRu: "Лоуренсий",
        nameLa: "Lawrencium",
        radioactive: true,
        class: "f-bottom actinides",
    },
    {
        symbol: "Rf",
        number: "104",
        ar: "[261]",
        oxidation: [],
        nameRu: "Резерфордий",
        nameLa: "Rutherfordium",
        radioactive: true,
        class: "d transition metal",
    },
    {
        symbol: "Db",
        number: "105",
        ar: "[262]",
        oxidation: [],
        nameRu: "Дубний",
        nameLa: "Dubnium",
        radioactive: false,
        class: "d transition metal",
    },
    {
        symbol: "Sg",
        number: "106",
        ar: "[263]",
        oxidation: [],
        nameRu: "Сиборгий",
        nameLa: "Seaborgium",
        radioactive: true,
        class: "d transition metal",
    },
    {
        symbol: "Bh",
        number: "107",
        ar: "[267]",
        oxidation: [],
        nameRu: "Борий",
        nameLa: "Bohrium",
        radioactive: true,
        class: "d transition metal",
    },
    {
        symbol: "Hs",
        number: "108",
        ar: "[269]",
        oxidation: [],
        nameRu: "Хассий",
        nameLa: "Hassium",
        radioactive: true,
        class: "d transition metal",
    },
    {
        symbol: "Mt",
        number: "109",
        ar: "[278]",
        oxidation: [],
        nameRu: "Мейтнерий",
        nameLa: "Meitnerium",
        radioactive: true,
        class: "d transition metal",
    },
    {
        symbol: "Ds",
        number: "110",
        ar: "[281]",
        oxidation: [],
        nameRu: "Дармштадтий",
        nameLa: "Darmstadtium",
        radioactive: true,
        class: "d transition metal",
    },
    {
        symbol: "Rg",
        number: "111",
        ar: "[281]",
        oxidation: [],
        nameRu: "Рентгений",
        nameLa: "Roentgenium",
        radioactive: true,
        class: "d transition metal",
    },
    {
        symbol: "Cn",
        number: "112",
        ar: "[262]",
        oxidation: [],
        nameRu: "Коперниций",
        nameLa: "Copernicium",
        radioactive: true,
        class: "d transition metal",
    },
    {
        symbol: "Nh",
        number: "113",
        ar: "[283]",
        oxidation: [],
        nameRu: "Нихоний",
        nameLa: "Nihonium",
        radioactive: true,
        class: "p",
    },
    {
        symbol: "Fl",
        number: "114",
        ar: "[289]",
        oxidation: [],
        nameRu: "Флеровий",
        nameLa: "Flerovium",
        radioactive: true,
        class: "p",
    },
    {
        symbol: "Mc",
        number: "115",
        ar: "[289]",
        oxidation: [],
        nameRu: "Московий",
        nameLa: "Moscovium",
        radioactive: true,
        class: "p",
    },
    {
        symbol: "Lv",
        number: "116",
        ar: "[293]",
        oxidation: [],
        nameRu: "Ливерморий",
        nameLa: "Livermorium",
        radioactive: true,
        class: "p",
    },
    {
        symbol: "Ts",
        number: "117",
        ar: "[294]",
        oxidation: [],
        nameRu: "Теннессин",
        nameLa: "Tennessine",
        radioactive: true,
        class: "p",
    },
    {
        symbol: "Og",
        number: "118",
        ar: "[294]",
        oxidation: ["0"],
        nameRu: "Оганесон",
        nameLa: "Oganesson",
        radioactive: true,
        class: "p",
    },
];

export default chemicalElements;